#!/usr/bin/python3

from sys import argv as av

def parse(content):
    
    # ips, date, method = content.partition(' ')
    # print(, end="")

def open_file(fileN):
    try:
        with open(fileN, "r") as f:
            content = f.read()
            parse(content)
    except FileNotFoundError:
        print("Error: The File {} not found".format(fileN));
    
def main():
    open_file(av[1])

if (len(av) != 2):
    print("Usage: ./loganalyzer + log file")
else:
    main()
